apiVersion: v1
kind: ConfigMap
metadata:
  namespace: roysahar
  name: wordpress-config
data:
  WORDPRESS_DB_HOST: "mariadb"
  WORDPRESS_DB_NAME: "wordpress"
  WORDPRESS_DB_USER: "wordpress"
  WORDPRESS_DB_PASSWORD: "wordpress"
  WORDPRESS_CONFIG_EXTRA: |
    define('WP_HOME','http://a79f5a0f68d764f44b8a738be4549817-701318126.us-east-1.elb.amazonaws.com/roysahar');
    define('WP_SITEURL','http://a79f5a0f68d764f44b8a738be4549817-701318126.us-east-1.elb.amazonaws.com/roysahar');
